---
name: Proselint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Proselint
        run: sudo apt-get install -y proselint
      - name: Run Proselint
        run: proselint */.md
